Support setting refresh token in cookie (#274)
* Support setting refresh token in cookie

This commit is the result of cherry-picking the following commits on top
of the current master branch, resolving conflicts, making some minor
changes and rebasing the lot into a single commit:

https://github.com/markitosgv/JWTRefreshTokenBundle/pull/199/commits/c6f67b097e7d80070464d3150459602c5f3b18e0
https://github.com/markitosgv/JWTRefreshTokenBundle/pull/199/commits/f9fbdf56e36fb7d64a6ac03516995a3448e34096
https://github.com/markitosgv/JWTRefreshTokenBundle/pull/199/commits/3267470c954c6de1000612967eb96cdf56325768

Resolved conflicts in:
	DependencyInjection/Configuration.php
	DependencyInjection/GesdinetJWTRefreshTokenExtension.php
	EventListener/AttachRefreshTokenOnSuccessListener.php
	README.md
	Request/RequestRefreshToken.php
	Resources/config/services.php
	spec/EventListener/AttachRefreshTokenOnSuccessListenerSpec.php
	spec/Request/RequestRefreshTokenSpec.php

* Fix tests for PHP 7.4 - Symfony 3.4.*

Fixes:

```
Error: Undefined class constant 'SAMESITE_NONE'
```

* Process feedback

* Update README.md

* Use snake_case in configuration options

* Add remove_token_from_body option to cookieSettings